// Package sqlite provides seed data for problems.
package sqlite

import (
	domain "leetcode-api/internal/domain/problem"
)

// DefaultTopics returns standard LeetCode topics
func DefaultTopics() []TopicModel {
	return []TopicModel{
		{Name: "Array", Slug: "array"},
		{Name: "String", Slug: "string"},
		{Name: "Hash Table", Slug: "hash-table"},
		{Name: "Math", Slug: "math"},
		{Name: "Dynamic Programming", Slug: "dynamic-programming"},
		{Name: "Sorting", Slug: "sorting"},
		{Name: "Greedy", Slug: "greedy"},
		{Name: "Depth-First Search", Slug: "depth-first-search"},
		{Name: "Binary Search", Slug: "binary-search"},
		{Name: "Tree", Slug: "tree"},
		{Name: "Breadth-First Search", Slug: "breadth-first-search"},
		{Name: "Two Pointers", Slug: "two-pointers"},
		{Name: "Stack", Slug: "stack"},
		{Name: "Linked List", Slug: "linked-list"},
		{Name: "Recursion", Slug: "recursion"},
		{Name: "Sliding Window", Slug: "sliding-window"},
		{Name: "Graph", Slug: "graph"},
		{Name: "Heap", Slug: "heap"},
		{Name: "Bit Manipulation", Slug: "bit-manipulation"},
		{Name: "Backtracking", Slug: "backtracking"},
	}
}

// SeedProblems returns initial problems for the database
func SeedProblems() []domain.Problem {
	return []domain.Problem{
		// Easy problems
		{
			Slug:           "two-sum",
			Title:          "1. Two Sum",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 52.3,
			Submissions:    14500000,
			Accepted:       7583500,
			Description:    `Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.`,
			Examples:       `Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]`,
			Constraints:    `2 <= nums.length <= 10^4`,
			StarterCode:    `{"javascript": "function twoSum(nums, target) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[2,7,11,15], 9]`, Expected: `[0,1]`, IsHidden: false},
				{Input: `[[3,2,4], 6]`, Expected: `[1,2]`, IsHidden: false},
			},
		},
		{
			Slug:           "palindrome-number",
			Title:          "9. Palindrome Number",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 56.7,
			Submissions:    8200000,
			Accepted:       4649400,
			Description:    `Given an integer x, return true if x is a palindrome, and false otherwise.`,
			Examples:       `Input: x = 121\nOutput: true`,
			Constraints:    `-2^31 <= x <= 2^31 - 1`,
			StarterCode:    `{"javascript": "function isPalindrome(x) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[121]`, Expected: `true`, IsHidden: false},
			},
		},
		{
			Slug:           "valid-parentheses",
			Title:          "20. Valid Parentheses",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 38.1,
			Submissions:    12000000,
			Accepted:       4572000,
			Description:    `Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.`,
			Examples:       `Input: s = "()"\nOutput: true`,
			Constraints:    `1 <= s.length <= 10^4`,
			StarterCode:    `{"javascript": "function isValid(s) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `["()"]`, Expected: `true`, IsHidden: false},
			},
		},
		{
			Slug:           "merge-two-sorted-lists",
			Title:          "21. Merge Two Sorted Lists",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 63.5,
			Submissions:    5400000,
			Accepted:       3429000,
			Description:    `Merge two sorted linked lists and return it as a sorted list.`,
			Examples:       `Input: l1 = [1,2,4], l2 = [1,3,4]\nOutput: [1,1,2,3,4,4]`,
			Constraints:    `The number of nodes in both lists is in the range [0, 50].`,
			StarterCode:    `{"javascript": "function mergeTwoLists(l1, l2) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[1,2,4], [1,3,4]]`, Expected: `[1,1,2,3,4,4]`, IsHidden: false},
			},
		},
		{
			Slug:           "best-time-to-buy-and-sell-stock",
			Title:          "121. Best Time to Buy and Sell Stock",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 47.6,
			Submissions:    9100000,
			Accepted:       4331600,
			Description:    `You are given an array prices where prices[i] is the price of a given stock on the ith day.`,
			Examples:       `Input: prices = [7,1,5,3,6,4]\nOutput: 5`,
			Constraints:    `1 <= prices.length <= 10^5`,
			StarterCode:    `{"javascript": "function maxProfit(prices) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[7,1,5,3,6,4]]`, Expected: `5`, IsHidden: false},
			},
		},
		{
			Slug:           "reverse-linked-list",
			Title:          "206. Reverse Linked List",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 75.8,
			Submissions:    6200000,
			Accepted:       4699600,
			Description:    `Given the head of a singly linked list, reverse the list, and return the reversed list.`,
			Examples:       `Input: head = [1,2,3,4,5]\nOutput: [5,4,3,2,1]`,
			Constraints:    `The number of nodes in the list is the range [0, 5000].`,
			StarterCode:    `{"javascript": "function reverseList(head) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[1,2,3,4,5]]`, Expected: `[5,4,3,2,1]`, IsHidden: false},
			},
		},
		{
			Slug:           "contains-duplicate",
			Title:          "217. Contains Duplicate",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 61.2,
			Submissions:    7500000,
			Accepted:       4590000,
			Description:    `Given an integer array nums, return true if any value appears at least twice in the array.`,
			Examples:       `Input: nums = [1,2,3,1]\nOutput: true`,
			Constraints:    `1 <= nums.length <= 10^5`,
			StarterCode:    `{"javascript": "function containsDuplicate(nums) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[1,2,3,1]]`, Expected: `true`, IsHidden: false},
			},
		},
		{
			Slug:           "maximum-subarray",
			Title:          "53. Maximum Subarray",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 50.3,
			Submissions:    8800000,
			Accepted:       4426400,
			Description:    `Given an integer array nums, find subarray with the largest sum, and return its sum.`,
			Examples:       `Input: nums = [-2,1,-3,4,-1,2,1,-5,4]\nOutput: 6`,
			Constraints:    `1 <= nums.length <= 10^5`,
			StarterCode:    `{"javascript": "function maxSubArray(nums) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[-2,1,-3,4,-1,2,1,-5,4]]`, Expected: `6`, IsHidden: false},
			},
		},
		// Medium problems
		{
			Slug:           "add-two-numbers",
			Title:          "2. Add Two Numbers",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 41.5,
			Submissions:    9200000,
			Accepted:       3818000,
			Description:    `You are given two non-empty linked lists representing two non-negative integers.`,
			Examples:       `Input: l1 = [2,4,3], l2 = [5,6,4]\nOutput: [7,0,8]`,
			Constraints:    `The number of nodes in each linked list is in the range [1, 100].`,
			StarterCode:    `{"javascript": "function addTwoNumbers(l1, l2) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[2,4,3], [5,6,4]]`, Expected: `[7,0,8]`, IsHidden: false},
			},
		},
		{
			Slug:           "longest-substring-without-repeating-characters",
			Title:          "3. Longest Substring Without Repeating Characters",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 34.5,
			Submissions:    11000000,
			Accepted:       3795000,
			Description:    `Given a string s, find the length of the longest substring without repeating characters.`,
			Examples:       `Input: s = "abcabcbb"\nOutput: 3`,
			Constraints:    `0 <= s.length <= 5 * 10^4`,
			StarterCode:    `{"javascript": "function lengthOfLongestSubstring(s) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `["abcabcbb"]`, Expected: `3`, IsHidden: false},
			},
		},
		{
			Slug:           "container-with-most-water",
			Title:          "11. Container With Most Water",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 54.8,
			Submissions:    6100000,
			Accepted:       3342800,
			Description:    `You are given an integer array height. Find two lines that together with the x-axis form a container.`,
			Examples:       `Input: height = [1,8,6,2,5,4,8,3,7]\nOutput: 49`,
			Constraints:    `n == height.length, 2 <= n <= 10^5`,
			StarterCode:    `{"javascript": "function maxArea(height) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[1,8,6,2,5,4,8,3,7]]`, Expected: `49`, IsHidden: false},
			},
		},
		{
			Slug:           "3sum",
			Title:          "15. 3Sum",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 33.8,
			Submissions:    7800000,
			Accepted:       2636400,
			Description:    `Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.`,
			Examples:       `Input: nums = [-1,0,1,2,-1,-4]\nOutput: [[-1,-1,2],[-1,0,1]]`,
			Constraints:    `3 <= nums.length <= 3000`,
			StarterCode:    `{"javascript": "function threeSum(nums) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[-1,0,1,2,-1,-4]]`, Expected: `[[-1,-1,2],[-1,0,1]]`, IsHidden: false},
			},
		},
		{
			Slug:           "letter-combinations-of-a-phone-number",
			Title:          "17. Letter Combinations of a Phone Number",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 58.2,
			Submissions:    4200000,
			Accepted:       2444400,
			Description:    `Given a string containing digits from 2-9 inclusive, return all possible letter combinations.`,
			Examples:       `Input: digits = "23"\nOutput: ["ad","ae","af","bd","be","bf","cd","ce","cf"]`,
			Constraints:    `0 <= digits.length <= 4`,
			StarterCode:    `{"javascript": "function letterCombinations(digits) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `["23"]`, Expected: `["ad","ae","af","bd","be","bf","cd","ce","cf"]`, IsHidden: false},
			},
		},
		{
			Slug:           "generate-parentheses",
			Title:          "22. Generate Parentheses",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 73.5,
			Submissions:    3900000,
			Accepted:       2866500,
			Description:    `Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.`,
			Examples:       `Input: n = 3\nOutput: ["((()))","(()())","(())()","()(())","()()()"]`,
			Constraints:    `1 <= n <= 8`,
			StarterCode:    `{"javascript": "function generateParenthesis(n) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[3]`, Expected: `["((()))","(()())","(())()","()(())","()()()"]`, IsHidden: false},
			},
		},
		{
			Slug:           "search-in-rotated-sorted-array",
			Title:          "33. Search in Rotated Sorted Array",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 40.1,
			Submissions:    5600000,
			Accepted:       2245600,
			Description:    `Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not.`,
			Examples:       `Input: nums = [4,5,6,7,0,1,2], target = 0\nOutput: 4`,
			Constraints:    `1 <= nums.length <= 5000`,
			StarterCode:    `{"javascript": "function search(nums, target) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[4,5,6,7,0,1,2], 0]`, Expected: `4`, IsHidden: false},
			},
		},
		{
			Slug:           "group-anagrams",
			Title:          "49. Group Anagrams",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 67.8,
			Submissions:    4500000,
			Accepted:       3051000,
			Description:    `Given an array of strings strs, group the anagrams together.`,
			Examples:       `Input: strs = ["eat","tea","tan","ate","nat","bat"]\nOutput: [["bat"],["nat","tan"],["ate","eat","tea"]]`,
			Constraints:    `1 <= strs.length <= 10^4`,
			StarterCode:    `{"javascript": "function groupAnagrams(strs) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[["eat","tea","tan","ate","nat","bat"]]`, Expected: `[["eat","tea","ate"],["tan","nat"],["bat"]]`, IsHidden: false},
			},
		},
		// Hard problems
		{
			Slug:           "median-of-two-sorted-arrays",
			Title:          "4. Median of Two Sorted Arrays",
			Difficulty:     domain.Hard,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 38.9,
			Submissions:    5100000,
			Accepted:       1983900,
			IsPremium:      false,
			Description:    `Given two sorted arrays nums1 and nums2, return the median of the two sorted arrays.`,
			Examples:       `Input: nums1 = [1,3], nums2 = [2]\nOutput: 2.00000`,
			Constraints:    `nums1.length == m, nums2.length == n, 0 <= m <= 1000`,
			StarterCode:    `{"javascript": "function findMedianSortedArrays(nums1, nums2) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[1,3], [2]]`, Expected: `2.0`, IsHidden: false},
			},
		},
		{
			Slug:           "regular-expression-matching",
			Title:          "10. Regular Expression Matching",
			Difficulty:     domain.Hard,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 28.4,
			Submissions:    4800000,
			Accepted:       1363200,
			IsPremium:      true,
			Description:    `Given an input string s and a pattern p, implement regular expression matching.`,
			Examples:       `Input: s = "aa", p = "a"\nOutput: false`,
			Constraints:    `1 <= s.length <= 20, 1 <= p.length <= 20`,
			StarterCode:    `{"javascript": "function isMatch(s, p) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `["aa", "a"]`, Expected: `false`, IsHidden: false},
			},
		},
		{
			Slug:           "merge-k-sorted-lists",
			Title:          "23. Merge k Sorted Lists",
			Difficulty:     domain.Hard,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 51.2,
			Submissions:    3400000,
			Accepted:       1740800,
			IsPremium:      false,
			Description:    `You are given an array of k linked-lists, merge all the linked-lists into one sorted linked-list.`,
			Examples:       `Input: lists = [[1,4,5],[1,3,4],[2,6]]\nOutput: [1,1,2,3,4,4,5,6]`,
			Constraints:    `k == lists.length, 0 <= k <= 10^4`,
			StarterCode:    `{"javascript": "function mergeKLists(lists) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[[1,4,5],[1,3,4],[2,6]]]`, Expected: `[1,1,2,3,4,4,5,6]`, IsHidden: false},
			},
		},
		{
			Slug:           "trapping-rain-water",
			Title:          "42. Trapping Rain Water",
			Difficulty:     domain.Hard,
			Category:       domain.CategoryAlgorithms,
			AcceptanceRate: 60.5,
			Submissions:    2900000,
			Accepted:       1754500,
			IsPremium:      false,
			Description:    `Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.`,
			Examples:       `Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]\nOutput: 6`,
			Constraints:    `n == height.length, 1 <= n <= 2 * 10^4`,
			StarterCode:    `{"javascript": "function trap(height) {\n  // Your code here\n}"}`,
			TestCases: []domain.TestCase{
				{Input: `[[0,1,0,2,1,0,1,3,2,1,2,1]]`, Expected: `6`, IsHidden: false},
			},
		},
		// Database problems
		{
			Slug:           "combine-two-tables",
			Title:          "175. Combine Two Tables",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryDatabase,
			AcceptanceRate: 72.4,
			Submissions:    2100000,
			Accepted:       1520400,
			Description:    `Write a solution to report the first name, last name, city, and state of each person.`,
			Examples:       `Output: firstName | lastName | city | state`,
			Constraints:    `Use SQL to solve this problem.`,
			StarterCode:    `{"sql": "SELECT * FROM Person"}`,
			TestCases:      []domain.TestCase{},
		},
		{
			Slug:           "second-highest-salary",
			Title:          "176. Second Highest Salary",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryDatabase,
			AcceptanceRate: 37.8,
			Submissions:    1800000,
			Accepted:       680400,
			Description:    `Write a solution to find the second highest salary from the Employee table.`,
			Examples:       `Output: SecondHighestSalary`,
			Constraints:    `Use SQL to solve this problem.`,
			StarterCode:    `{"sql": "SELECT * FROM Employee"}`,
			TestCases:      []domain.TestCase{},
		},
		{
			Slug:           "employees-earning-more-than-their-managers",
			Title:          "181. Employees Earning More Than Their Managers",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryDatabase,
			AcceptanceRate: 68.9,
			Submissions:    1500000,
			Accepted:       1033500,
			Description:    `Write a solution to find the employees who earn more than their managers.`,
			Examples:       `Output: Employee`,
			Constraints:    `Use SQL to solve this problem.`,
			StarterCode:    `{"sql": "SELECT * FROM Employee"}`,
			TestCases:      []domain.TestCase{},
		},
		// Shell problems
		{
			Slug:           "word-frequency",
			Title:          "192. Word Frequency",
			Difficulty:     domain.Medium,
			Category:       domain.CategoryShell,
			AcceptanceRate: 25.6,
			Submissions:    800000,
			Accepted:       204800,
			Description:    `Write a bash script to calculate the frequency of each word in a text file.`,
			Examples:       `Output: the 4\nis 3\nsunny 2`,
			Constraints:    `Use bash to solve this problem.`,
			StarterCode:    `{"bash": "# Read from the file words.txt and output the word frequency list to stdout."}`,
			TestCases:      []domain.TestCase{},
		},
		{
			Slug:           "valid-phone-numbers",
			Title:          "193. Valid Phone Numbers",
			Difficulty:     domain.Easy,
			Category:       domain.CategoryShell,
			AcceptanceRate: 26.1,
			Submissions:    750000,
			Accepted:       195750,
			Description:    `Given a text file file.txt that contains a list of phone numbers, write a one-liner bash script to print all valid phone numbers.`,
			Examples:       `Output: 987-123-4567`,
			Constraints:    `Use bash to solve this problem.`,
			StarterCode:    `{"bash": "# Read from the file file.txt and output all valid phone numbers to stdout."}`,
			TestCases:      []domain.TestCase{},
		},
	}
}
