import { Room, RoomParticipant, Level } from '@/types';

// Mock participants
const mockParticipants: RoomParticipant[] = [
    {
        id: '1',
        name: 'John',
        avatarUrl: 'https://i.pravatar.cc/150?u=john',
        nativeLanguage: 'English',
        learningLevel: 'B2',
        country: 'USA',
        countryFlag: '🇺🇸',
        isMuted: false,
        isSpeaking: true,
        joinedAt: new Date(),
    },
    {
        id: '2',
        name: 'Maria',
        avatarUrl: 'https://i.pravatar.cc/150?u=maria',
        nativeLanguage: 'Spanish',
        learningLevel: 'B1',
        country: 'Spain',
        countryFlag: '🇪🇸',
        isMuted: true,
        isSpeaking: false,
        joinedAt: new Date(),
    },
    {
        id: '3',
        name: 'Yuki',
        avatarUrl: 'https://i.pravatar.cc/150?u=yuki',
        nativeLanguage: 'Japanese',
        learningLevel: 'A2',
        country: 'Japan',
        countryFlag: '🇯🇵',
        isMuted: false,
        isSpeaking: false,
        joinedAt: new Date(),
    },
    {
        id: '4',
        name: 'Ahmed',
        avatarUrl: 'https://i.pravatar.cc/150?u=ahmed',
        nativeLanguage: 'Arabic',
        learningLevel: 'B2',
        country: 'Egypt',
        countryFlag: '🇪🇬',
        isMuted: false,
        isSpeaking: false,
        joinedAt: new Date(),
    },
    {
        id: '5',
        name: 'Sophie',
        avatarUrl: 'https://i.pravatar.cc/150?u=sophie',
        nativeLanguage: 'French',
        learningLevel: 'C1',
        country: 'France',
        countryFlag: '🇫🇷',
        isMuted: false,
        isSpeaking: false,
        joinedAt: new Date(),
    },
];

export const mockRooms: Room[] = [
    {
        id: '1',
        name: 'Travel Stories',
        topic: 'Share your favorite travel experiences and dream destinations',
        level: 'A2',
        type: 'public',
        hostId: '1',
        maxParticipants: 8,
        participantCount: 5,
        participants: mockParticipants.slice(0, 5),
        tags: ['travel', 'culture', 'adventure'],
        createdAt: new Date(),
    },
    {
        id: '2',
        name: 'Business English Practice',
        topic: 'Practice professional communication and business vocabulary',
        level: 'B2',
        type: 'public',
        hostId: '2',
        maxParticipants: 6,
        participantCount: 3,
        participants: mockParticipants.slice(0, 3),
        tags: ['business', 'career', 'professional'],
        createdAt: new Date(),
    },
    {
        id: '3',
        name: 'Daily Chit-Chat',
        topic: 'Casual conversations about everyday life',
        level: 'A1',
        type: 'public',
        hostId: '3',
        maxParticipants: 10,
        participantCount: 7,
        participants: mockParticipants,
        tags: ['casual', 'daily', 'beginner-friendly'],
        createdAt: new Date(),
    },
    {
        id: '4',
        name: 'Debate Club',
        topic: 'Discuss controversial topics and practice argumentation',
        level: 'C1',
        type: 'public',
        hostId: '4',
        maxParticipants: 8,
        participantCount: 4,
        participants: mockParticipants.slice(0, 4),
        tags: ['debate', 'opinion', 'advanced'],
        createdAt: new Date(),
    },
    {
        id: '5',
        name: 'Movie Discussion',
        topic: 'Talk about your favorite movies and TV shows',
        level: 'B1',
        type: 'public',
        hostId: '5',
        maxParticipants: 12,
        participantCount: 6,
        participants: mockParticipants.slice(0, 6),
        tags: ['movies', 'entertainment', 'series'],
        createdAt: new Date(),
    },
    {
        id: '6',
        name: 'Tech Talk',
        topic: 'Discuss technology, gadgets, and the future',
        level: 'B2',
        type: 'public',
        hostId: '1',
        maxParticipants: 8,
        participantCount: 2,
        participants: mockParticipants.slice(0, 2),
        tags: ['technology', 'programming', 'gadgets'],
        createdAt: new Date(),
    },
];

export function getRoom(id: string): Room | undefined {
    return mockRooms.find((room) => room.id === id);
}
